### ISSUE TITLE
无法运行，运行时直接报错。

### ISSUE THREAD

**Issue by wertyac** [AlanLee1996/wenda-webui#19]
VITE v4.3.9  ready in 694 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: http://192.168.199.222:5173/
  ➜  press h to show help
Error: The following dependencies are imported but could not be resolved:

  element-plus/es/locale (imported by /opt/wenda-webui/src/App.vue?id=0)

Are they installed?
    at file:///opt/wenda-webui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44188:23
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///opt/wenda-webui/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43597:38

ENV：Ubuntu 22.04.1
nodejs：v18.16.0

检查了版本和楼主的都一样的。

**Comment by AlanLee1996** [comment]
环境删了重装
