### ISSUE TITLE
怎么实现demo_img里的两个示例效果？

### ISSUE THREAD

**Issue by QDPeng** [AlanLee1996/wenda-webui#25]
你好，
我下载了rwkv-4-pile-3b，并使用RWKV-4-Pile-3B-Chn-testNovel-done-ctx2048-20230312.pth模型启动wenda项目工程，知识库使用rtst格式的模型：model/m3e-base
然后配置wenda-webui工程，启动web页面进行测试，发现模型识别效果很差，没有示例效果好，请问如何操作才能实现demo_img目录的两个示例效果？
换别的模型还是额外需要哪里配置？你的demo中的测试是用的哪个模型？有详细链接吗？

谢谢！！

**Comment by AlanLee1996** [comment]
换模型，用gpt最佳
